### ISSUE TITLE
Publish a new version on crates.io pointing people to the git repo

### ISSUE THREAD

**Issue by osa1** [osa1/tiny#140]
We will no longer publish new versions on crates.io so we should publish a new version (probably 0.5) pointing people to this repository. When run it should print something like:

```
Starting with 0.5 tiny is no longer published on crates.io.
Please install with

    cargo install --git https://github.com/osa1/tiny.git

If you encounter any problems please see README at https://github.com/osa1/tiny
```

**Comment by jedahan** [comment]
Now that tiny builds on stable, would you be open to start re-publishing on crates.io? Or are there other reasons you prefer not to publish the crate?

**Comment by osa1** [comment]
Requiring nightly toolchain is not the reason for not publishing on crates.io. The reason is tiny consists of 9 crates, and IIRC (I may be wrong, or it may have been changed since last time I checked) all of these packages need to be published on crates.io for tiny to be published on crates.io. In addition to being a lot of work it pollutes crates.io with useless packages.

Also, I think running 

```
cargo install --git https://github.com/osa1/tiny.git
```

instead of 

```
cargo install tiny
```

is not too bad (though you have to remember the git repo), so I thought it's not worth the effort.

Why do you think publishing on crates.io would be useful? Is it only because the `cargo install ...` command is shorter or are there other reasons?

I should check again whether I have to publish all dependencies on crates.io to publish a package on crates.io.

**Comment by jedahan** [comment]
Personally, its purely a familiarity thing - I install bat, fd, exa, rg, all through `cargo install bat/exa/fd-find/ripgrep`.

For initial installs, I actually like the explicitness and flexibility of `cargo install --git https://github.com/osa1/tiny.git`, though would prefer it to use #sometag as recommended for stable. It would be really nice if the ecosystem started using full URLs for "end-user programs" and crates just for crates.

That said, for updating, its much nicer having crates published on crates.io, since a user can know they are getting the 'latest stable release'. It also works well with tools like [cargo-update](https://github.com/nabijaczleweli/cargo-update).

If you are cool with force-updating a particular tag on master when making releases, such that a user could `cargo install --git https://github.com/osa1/tiny.git#stable` then that would pretty much erase the only meaningful difference I could come up with.

**Comment by osa1** [comment]
Moved the discussion to #257.
