### ISSUE TITLE
Why is hostname required?

### ISSUE THREAD

**Issue by SamHH** [osa1/tiny#150]
`hostname` appears to be a required field in the config for each server you define, why is that?

**Comment by osa1** [comment]
I wasn't even aware that you can connect without a hostname! I checked the RFCs again and indeed they're confusing. RFC 1459 says:

```
4.1.3 User message

      Command: USER
   Parameters: <username> <hostname> <servername> <realname>

   The USER message is used at the beginning of connection to specify
   the username, hostname, servername and realname of s new user.  It is
   also used in communication between servers to indicate new user
   arriving on IRC, since only after both USER and NICK have been
   received from a client does a user become registered.
```

Note that in the syntax "hostname" is not optional. The example RFC gives:

```
USER guest tolmoon tolsun :Ronnie Reagan
```

(tiny never sent a `USER` message according to this syntax, but still, we always sent `hostname`)

Then RFC 2812 updates:

```
3.1.3 User message

      Command: USER
   Parameters: <user> <mode> <unused> <realname>

   The USER command is used at the beginning of connection to specify
   the username, hostname and realname of a new user.
```

Note that there's no `hostname` here, and the example is similar to what tiny sends:

```
USER guest 0 * :Ronnie Reagan
```

So it turns out we don't need hostname at all, we can simply send

```
USER <nick> 0 * :<realname>
```

which I just tried, and it works.

Fix coming.
