### ISSUE TITLE
Option to ignore joins/quits

### ISSUE THREAD

**Issue by endeav0r** [osa1/tiny#18]
irssi has /ignore which give the option to ignore joins/quits/parts on a per-channel basis. Turning off notifications of joins/quits/parts and all of that altogether would be enough.

Watching all the joins/parts/quits in busy channels can be a bit much, and distracting.

As an aside, I don't want to spam your project with issues for things. If these aren't helpful right now, please let me know.

**Comment by osa1** [comment]
> Watching all the joins/parts/quits in busy channels can be a bit much, and distracting.

Indeed, this is why I implemented showing parts/joins etc. in single line, in a concise format. I can imagine even that being too noisy on some channels.

> As an aside, I don't want to spam your project with issues for things. If these aren't helpful right now, please let me know.

That's fine, keep them coming!

This doesn't sound too hard to implement so if someone wants to contribute this feature I can provide help.

**Comment by meain** [comment]
@osa1 Could you direct me to which is the file that I should be looking for to add this?

**Comment by osa1** [comment]
Sure. You'll need to work on modules under `tui/`. To summarize:

- `tabbed`: Keeps tabs. Each tab is a `MessagingUI`.
- `messaging`: Implements `MessagingUI`. A `MessagingUI` is basically an input field (`text_field`) + an area for showing messages + join/part stuff (`msg_area`).
- `msg_area` just keeps a vector of `Line`s.

You'll need to modify one or more of these files.

But before that we should design the feature.

I can see two ways of implementing this:

1. Add a boolean switch to `MsgArea` for whether to _show_ join/parts or not. Add another flag to `Line` for whether the line is a join/part or not. Then, depending on these two flags, decide whether to draw a line or skip it when rendering `MsgArea`.

2. Add a boolean switch (not sure where) for whether to _add_ join/part messages or not. If this flag is off, we simply do not add join/part lines to `MsgArea`.

(1) requires changes in the TUI widgets, (2) could be implemented with a simple flag in `tui/mod.rs` + some `if` expression in a few places. (2) is simpler, but (1) has the advantage that we could toggle join/part messages with a command and we'd see join/parts that arrived since we disabled them.

**Comment by osa1** [comment]
How about this?

- Add a flag to `MessagingUI`
- Check that flag in `MessagingUI::join` and `MessagingUI::part`. Based on the flag run the `self.msg_area...` lines.
- Add a method to `MessagingUI` and `TUI` for toggling the flag.

If you're going with (2) (which is fine by me) you shouldn't need to change anything in `Line`.

**Comment by meain** [comment]
@osa1 
Worked on method (2).
I am implemented it to toggle on `/ignore`. Do you wan't to have different commands for turning on and off or is this good?

**Comment by osa1** [comment]
Cool. I think it's `/ignore` is OK.
