### ISSUE TITLE
Panic in pinger.rs

### ISSUE THREAD

**Issue by e00E** [osa1/tiny#185]
I was editing a message using the text editor through the `C-x` hotkey. When I closed the editor I saw this message interleaved with the channel text (probably because it went to stderr). Despite the panic tiny did not actually crash. It displayed the normal ping timeout message and successfully reconnected afterwards.

> panicked at 'called `Result::unwrap()` on an `Err` value: Closed(SendPing)', libtiny_client/src/pinger.rs:40:9

https://github.com/osa1/tiny/blob/f8477c322a0eb464072542f75c50ecfeb587bbd0/libtiny_client/src/pinger.rs#L40

**Comment by osa1** [comment]
Thanks for reporting. I think this is just a manifestation of a long-standing problem with the `C-x` implementation. It currently stops *all* tasks, that includes the tasks that drive connections, timer tasks for checking connectivity etc. If you spend long-enough time in your editor after `C-x` it causes all kinds of problem.

The solution should be to run the editor in a new thread, allowing background tasks to run. This may be as easy as wrapping the call with `tokio::task::spawn_blocking`. Only difficulty with this is that the TUI task needs to wait for the blocking task to return.

**Comment by osa1** [comment]
I thought a little bit about how to best fix this isssue with `C-x`. Here's an idea:

- First of all `termbox` should support `present()` when suspended. It'd basically just update the internal buffer but do not write the buffer to the tty when suspended, until it's activated again.
  This is easy to implement as `termbox` already works without a tty (used in tests).

- Once we have that we'll be able to suspend the TUI while still being able to do updates. This will allow us to show `$EDITOR` in a new thread while all the connection tasks update the TUI.

- TUI is not `Send` or `Sync` so we won't be able to have a reference to it in the `$EDITOR` thread. Instead we will send an event to the TUI via the event channel. The problem here is that normally TUI only has the receiver end of this channel. So to be able to do it we'll also keep a sender in TUI, and clone and pass it to the `$EDITOR` thread. This will also require a new event type.

After this it should be possible to run `$EDITOR` for hours if we wanted.
