### ISSUE TITLE
Logger spamming mentions tab

### ISSUE THREAD

**Issue by ii8** [osa1/tiny#203]
Tiny fills the mentions tab with messages of the form:

```
Logger error: Logger: can't find chan #voidlinux in server chat.freenode.net
```

voidlinux and freenode are an example here, this happens with a lot of channels and servers.
There are so many of these messages I can't see when people actually mention me.
The channels actually do exists and everything works fine, I am able to talk there.

Also, the message looks a bit silly with `Logger` there twice.

https://github.com/osa1/tiny/blob/9609a9a43ec53a204059bc810791655ae8943f5f/libtiny_logger/src/lib.rs#L317

**Comment by osa1** [comment]
Thanks for reporting.

This log line is printed when there's a problem creating the log file for the channel, and if you scroll up in the "mentions" tab you should be able to see what the problem was (e.g. "disk is full"). I now refactored the logger a little bit to only report IO errors so you won't be seeing "can't find chan" messages anymore, you'll only see IO errors. I don't want to disable IO error logging in "mentions" tab as those need attention from the user.

Could you try again with the `master` branch and let me know how it works now?

For developers, if you want to see more detailed logs, you can run tiny with:

```
$ RUST_LOG=libtiny_logger=debug ./target/debug/tiny 2>stderr
```

and see the debug logs in `stderr` file.

> Also, the message looks a bit silly with Logger there twice.

Fixed.

**Comment by ii8** [comment]
Yes, when I scroll up it takes quite a while but eventually there is:
```
Logger error: Os { code: 2, kind: NotFound, message: "No such file or directory" }
```

That makes sense, I removed the `log_dir` line in the config in an attempt to disable logging but I guess that's not how that works.
Is there some correct way to disable logging?

I'm struggling to build master from source atm because I don't have the right rust compiler, I'll try again later.

**Comment by osa1** [comment]
That is how you're supposed to disable logging, yes. I'll test and see if it works, and fix if not.

**Comment by osa1** [comment]
> I'm struggling to build master from source atm because I don't have the right rust compiler, I'll try again later.

Perhaps we should generate binaries for all commits, using Github actions. We currently only do this for tagged commits (releases).

**Comment by osa1** [comment]
> I removed the log_dir line in the config in an attempt to disable logging but I guess that's not how that works.

I just tried this, and I can see that logging is disabled as expected if I remove or comment-out the `log_dir` line. I see no errors or debug logs printed anywhere. Can you try again and let me know if it works?

**Comment by ii8** [comment]
Yes, the error is no longer printed for me either. However it also does not tell me if the client is disconnected anymore, I can loose internet connection and just keep sending messages in tiny and I'd never know it wasn't working.
It does catch up in sending them after I reconnect though.
Perhaps now too many logs are suppressed?

**Comment by ii8** [comment]
Looks like everything works.
Thank you!
