### ISSUE TITLE
Tiny channel

### ISSUE THREAD

**Issue by Kabouik** [osa1/tiny#218]
Is there a channel to talk about `tiny`? Sometimes it would be easier to talk about features/issues without sending notifications to everyone, or to actually check quickly if the topic deserves a new issue. I checked `CONTRIBUTING.md` but it's empty at the moment.

**Comment by osa1** [comment]
We used to have a channel on Mozilla IRC server, but that server is gone now. We could open a Gitter channel so that people could join with a browser or with an IRC client via https://irc.gitter.im. Alternatively we could wait for [GitHub discussions][1] (no ETA yet though). Finally we could always register a channel in one of the widely-used IRC servers (e.g. Freenode).

Any opinions? I think my order of preference is (1) Gitter (2) GitHub discussions (we'll have to wait for this) (3) IRC channel.

[1]: https://github.blog/2020-05-06-new-from-satellite-2020-github-codespaces-github-discussions-securing-code-in-private-repositories-and-more/#discussions

**Comment by trevarj** [comment]
I like that order of preference too. Github Discussions will be useful.

Is it just me, or does it feel like chats are more fragmented than ever? It seemed like overnight everyone moved from IRC to Discord, Mattermost, Gitter, Riot.im, etc etc :weary:

**Comment by osa1** [comment]
It's a mess, yes. I currently have Discord, Slack, and IRC open. That's 2 too many. I used to have Gitter too but I'm using the IRC bridge now.

**Comment by Kabouik** [comment]
Any solution with a way to connect through IRC sounds cool to me. Just a minor thought though: while Gitter would be convenient for both IRC and web use, it's also less straightforward to connect to it since it requires an account and a token. I assume users who have questions about `tiny` already know their way around IRC and popular networks like Freenode, so a channel requiring no Gitter token would be nice too. Maybe have solution (1) and bridge it to (3)? Also (2) sounds cool but no ETA as you said, and I'm sure some users expect to find an IRC room for their IRC client if there's a community.

**Comment by trevarj** [comment]
I do agree that a freenode channel is more accessible. It wasn't too hard to set up the Gitter irc bridge. I did it the other day to test it out when it wasn't working :laughing:. As long as it's noted in the `README.md` and `CONTRIBUTING.md` then it should be ok.

**Comment by jedahan** [comment]
:+1: for an irc channel, especially as the project is an irc client. I'm hanging out on freenode #osa1-tiny until something more official pops up.

**Comment by osa1** [comment]
Thanks for the suggestions. I couldn't register a channel in Freenode as the name #tiny has already been registered, and it's invite only so we can't even borrow it. I registered it in OFTC instead.
