### ISSUE TITLE
Is there a max buffer size?

### ISSUE THREAD

**Issue by dontlaugh** [osa1/tiny#219]
Nice client!

I'm using tiny on a multi-user system in tmux, and i want to make sure I don't use an unbounded amount of memory if I just leave it open all day.

**Comment by osa1** [comment]
Thanks for the feedback!

We currently don't have this. This is actually quite easy to implement, the only reason why I haven't done so so far is because even though I leave my client running too (but not for months, in the worst case for a week or two, I think) I never see it using more than 0.1% or 0.2% of memory on my system.

For leaving it running for months on a multi-user system I agree that it might be useful and even necessary.

We can also easily make this configurable (e.g. max lines to keep in a tab).

Marking as "feature request". If anyone wants to implement I'd be happy to help. If not then I might do this myself this weekend.
