### ISSUE TITLE
Rendering glitches when switching tabs

### ISSUE THREAD

**Issue by alxgnon** [osa1/tiny#366]
When switching tabs, I get visual glitches that stick around until I resize the window.

I've tracked down the specific commit where this issue appeared. This issue has appeared since https://github.com/osa1/tiny/commit/33df77e27b180f777782c7803651022e22602dee .

![Screenshot_2021-11-24_13-19-59](https://user-images.githubusercontent.com/4480082/143294098-b804972a-8da4-4416-ae18-14dcb3973bc6.png)

**Comment by osa1** [comment]
Thanks for reporting and tracking down the commit.

I'm surprised that this started with 33df77e, I don't see anything in that commit that could cause something like this.

Is it possible for you to give instructions to replicate the problem?

I reverted that commit in branch `revert_33df77e`. Could you please try that branch and let me know if the problem really disappears when that commit is reverted?

**Comment by alxgnon** [comment]
Everything works fine on the revert branch. This shows that the specific commit is the source of the problem.

Terminal emulator: Alacritty
Server: ZNC

Steps to Reproduce:
1. Launch tiny to connect to a ZNC instance.
2. Use alt-2 to switch to the server tab.
3. Run `/msg *backlog #channel 50` to fetch the backlog.
4. Use alt-3 to switch to the first channel.

Expected behaviour:
The channel contents are printed cleanly with no visual artifacts.

Actual behaviour:
The channel buffer contains garbage characters from the previous tab. The garbage is found at the end of lines that are shorter then the ones from the previous tab.

I was not able to reproduce this bug without running the backlog command on ZNC.

**Comment by osa1** [comment]
Thanks for the details. I installed ZNC, installed backlog plugin, connected to irc.oftc.net #tiny, and tried your commands. Probably because I don't have any backlog, it doesn't cause any problems. I also tried the same thing in alacritty instead of my default terminal.

Just to understand this better, `alt-3` is not the backlog channel, right? And if you skip step (3) and do alt-3, it works fine?

So you need to create the backlog channel, but don't need to switch to it?

In the screenshot you don't have a `*backlog` channel, but if I run `/msg *backlog #channel 50` it creates a `*backlog` tab in tiny. Why do you not have the tab?

I think we should be able to debug this using tiny debug logs. Could you please try these and share the results?

- Build tiny: `cargo build`
- Make sure you have `log_dir` set in `~/.config/tiny/config.yml`: `log_dir: '/home/<user>/tiny_logs'`
- Clear old debug logs (if any): `rm <tiny log directory>/tiny_debug_logs.txt`
- Run tiny: `TINY_LOG=debug ./target/debug/tiny`
- Run your repro, see the glitches, close tiny

Now if you look at `<tiny log directory>/tiny_debug_logs.txt`, you will see the parsed messages coming from znc. If the problem starts happening after `/msg *backlog #channel 50`, you should see some messages coming from user `znc@znc.in`. Some of those messages should have some IRC formatting characters or ASCII control characters. Some of those should be the issue. If you could share some of the messages (make sure to redact text parts) we should be able to debug this.

**Comment by alxgnon** [comment]
alt-3 is the first channel I am connected to in the server. If I don't fetch the backlog, everything seems to be fine.(?) Haven't seen what happens if I let the screen fill with text naturally.

The reason I didn't have a backlog tab in the screenshot is because, usually I call an alias for the backlog command, and when I do so it doesn't open the *backlog plugin chat buffer.

This is what I got for the logs. I edited all the messages to remove the text and names. I didn't find any strange control characters or anything.
[tiny_debug_logs.txt](https://github.com/osa1/tiny/files/7600559/tiny_debug_logs.txt)

I don't see anything that could help in the logs.

**Comment by osa1** [comment]
Thanks @alxgnon, I figured it out from the log file you shared: it's the new line characters znc backlog plugin is sending.

Interestingly, when I tried it it didn't add new line to the end of the messages. Maybe because they fixed it? I installed it from the source (current master branch).

Could you please try the branch `issue_366` and let me know if it fixes the issue?

**Comment by osa1** [comment]
@alxgnon just pushed one more commit -- I forgot to remove a debug print in the previous version.

**Comment by alxgnon** [comment]
Works!

**Comment by osa1** [comment]
Fix is now in master :-)
