### ISSUE TITLE
autojoin not working with soju bouncer

### ISSUE THREAD

**Issue by eoli3n** [osa1/tiny#377]
When I connect to my soju bouncer, instead of irc.libera.chat directly, channels in ``join`` config are ignored.

**Comment by eoli3n** [comment]
Maybe that's a normal behaviour, as soju bouncer is actually keeping channels open server side

**Comment by osa1** [comment]
Since autojoin works for IRC servers, and soju should be acting like an IRC server, I think this is probably not a bug in tiny.

What happens when you connect to an IRC server is, tiny sends a `JOIN #channel` message to the server, and server replies with `JOIN #channel` when the join is successful. That's when we create the tab for the channel.

My guess is, since soju is already connected to the server, it doesn't get a `JOIN` response from the server (because it doesn't send one, it's already in the channel), and it also doesn't reply to the client (in this case tiny) with `JOIN`. So tiny doesn't create the tab for the channel because from tiny's point of view JOIN has not been successful.

Does soju not send the client channel history when you connect? When you receive a message for a channel tiny should be creating the tab for it.

**Comment by eoli3n** [comment]
It does send channel history yes.
Maybe I was misunderstanding how it is supposed to work, I now need to manage my channels inside soju, as tiny acts like a simple client for it.
Let's close this, thanks for answering !
