### ISSUE TITLE
Config for other terminals - (my hack for Backspace in suckless st)

### ISSUE THREAD

**Issue by anxiousmodernman** [osa1/tiny#9]
I use a custom fork of the suckless simple terminal (st). 

Backspace didn't work (it worked in Terminator, though) until I added this.
https://github.com/gloriousfutureio/tiny/commit/6d2dfe29401fca2ab1c5ac5f00a18404dfcbe689

Clearly this is a hack, but it was fun to track down and fix, since I'm new to Rust, X, and terminal emulators generally.

I can keep rebasing  off origin/master to stay current, but is it feasible to have an "override" or some sort of dynamic config? Off top, something like

```yaml
keys:
  - event: Backspace
    seq:
      - 8
```

This could "add" to a config that uses the XTERM defaults but adds to/replaces events raised for certain byte sequences.

**Comment by osa1** [comment]
Hi @anxiousmodernman ,

May I ask what changes did you do in your st fork? I just tried with st HEAD (cloned from  git://git.suckless.org/st) and backspace worked fine. I tried a bunch of other key bindings and they all seem to work. I have a program for testing byte sequences generated by terminal for key presses, you can see it in action in st:

![screenshot_2017-06-23_21-23-40](https://user-images.githubusercontent.com/448274/27495371-5466fc20-585a-11e7-8801-e1dea7d99458.png)

We could certainly implement overriding mapping of byte sequences to keys in config file, but I think most terminals these days use same byte sequences for keys as xterm (I tried konsole, gnome-terminal, xfce4-terminal, iterm2, st...) so I think that feature may not worth the additional complexity. Let's first figure why your st fork isn't behaving like st HEAD. If that can't be worked out maybe we can add a mapping for byte sequence `[8]` to backspace, because that's sequence is currently unused and I don't see any useful keys that generated that sequence (only key combination that generated it on my system was ctrl + h).

**Comment by anxiousmodernman** [comment]
I forked-a-fork a few months ago and recently pushed it up into my personal repo. I'll recompile the tip of master and just test it and get back to you. My version is here: https://github.com/anxiousmodernman/st

**Comment by anxiousmodernman** [comment]
Ah shoot you were right. Recompiling the tip of master for st worked, but only inside tmux (which is fine for me; i get unsupported terminal panic from tiny otherwise).

They've restructured the codebase of st, so I will have to find the differences in config.def.h (my guess)

**Comment by osa1** [comment]
> i get unsupported terminal panic from tiny otherwise

For the record, I don't get this error with st HEAD. I tried with and without tmux and tiny worked fine.

**Comment by anxiousmodernman** [comment]
forgive me: in my tmux I set

* TERM=screen-256color

st recompiled run without tmux yields

```
TERM=st-256color   
```

![unsupported](https://user-images.githubusercontent.com/396004/27496234-e1d6be46-581a-11e7-8f29-b4a34d5c9f9a.png)

**Comment by anxiousmodernman** [comment]
In any case. I've reproduced the good behavior from tiny, so it looks like I can handle this bug at the terminal emulator level instead of hacking tiny. I like all my st customizations, so I'll really try to track down the difference with `master` and apply them. My reason for forking was to make myself write C code, anyway. I'll try to find a patch that fixes it for me and I'll paste it here. But for now it looks like this isn't a bug in tiny.

**Comment by osa1** [comment]
OK, closing...
